name: MegaCreepers
main: com.frostcraft.megacreepers.MegaCreepers
version: 1.1
commands:
  mcreepers:
    description: MegaCreepers admin menu
    usage: Use /mcreepers
    permission: megacreepers.admin
    permission-message: You do not have permission to use this command.
permissions:
    megacreepers.admin:
        description: Megacreepers admin permission.
        default: op